[ChipDspMap]
enable=0
[Comparison]
Enable=0
Parameter=""%s" "%s""
Policy=1
Program=C:\Program Files (x86)\Beyond Compare 3\BCompare.exe
[Debug]
Data=enable:level=-
[Download_Packet]
Floader=
ShowConfirmDialog=1
UnpacketDir=.\
packet=D:\River\DTU_FCT\Info\Configuration\PAC_File_path\RX01_N58_App_v1.0.0.pac
[EraseFlash]
[FirstMode]
Enable=0
FirstMode=0x0
SupportFeaturePhone=0
[GUI]
BaudRates=57600,115200,230400,460800,921600,1000000,2000000,3250000,4000000
CanEdit=1
CanSelect=1
ClosePortFlag=0
CmdPackage=0
FileFilter=All file(*.*)|*.*|Image file (*.bin;*.img)|*.bin;*.img||
FileMode=0
InDLProcess=1
MarkLastState=0
PacketMode=1
PowerManageFlag=0
PowerManageInterval=10
SafetyTipsMsg=1
ScriptControl=0
ScriptControlStop=1
ShowFailedMsgBox=0
ShowPacPath=0
ShowRate=1
ShowSecurityTips=0
SkipBackupNV=0
UserGuide = UNISOC Download User Guide V4.1.pdf
[Mes]
Enable=0
[NV]
FileNameWithSN=1
SaveToLocalFlag=0
PrintNVItem=
PrintOffset=0
EnableReadNV=0
[Options]
CheckMatch=0
DDRCheck=0
EraseAll=0
FlashPageType=0
KeepCharge=0
PowerOff=1
ReadChipUID=0
Repartition=0
Reset=0
SelfRefresh=0
UartDownload=0
WriteEfuse=0
ReadMCPType=0
EnableLog=0
EnableSecureBoot=0
EnableEndProcess=0
ReadPartition=0
DumpUbootLog=0
VpacCheck=0
CheckNvItemReadCrc=0
Enable7e2DumpLog=0
ComparePartitionInfo=1
[PartitionValue]
ReadEnable=0
ReadOffset=0x0
ReadPartitionID=miscdata
ReadSize=0x0
WriteEnable=0
WriteOffset=0x0
WritePartitionID=miscdata
WriteSize=0x4
WriteValue=TEST
[PortSetting]
EnableFilter=1
EnableFixedPort=0
FilterPort=1,2
FixedPortList=
[ReadFlash]
flash00=0:0x8000C0:0xFF40:D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ReadFlash\fdl1.sign.img
flash01=0:0x60000000:0x10000:D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ReadFlash\boot.sign.img
flash02=0:0x60010000:0x260000:D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ReadFlash\Customer_cat1bis_novolte.sign.img
flash03=0:0x60270000:0x1C0000:D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ReadFlash\hello_flash.img
flash04=0:0x60560000:0x280000:D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ReadFlash\cat1_UIS8915DM_BB_RF_SS_NoVolte_cus.img
flash05=0:0xFE000006:0x53595346:D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ReadFlash\_only.bin
flash06=0:0xFE000001:0x0:D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ReadFlash\_only.bin
flash07=0:0xFE000003:0x20000:D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ReadFlash\cat1_UIS8915DM_BB_RF_SS_NoVolte_cus_nvitem.bin
flash08=0:0xFE000004:0x0:D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ReadFlash\cat1_UIS8915DM_BB_RF_SS_NoVolte_cus_prepack.cpio
flash09=0:0xFE000002:0x100:D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ReadFlash\miscdata.bin
[Report]
DUTID=0
Type=0
enable=0
[SN]
AutoGenerateSN=1
AutoStartAfterInputSN=1
NeedPhaseCheck=0
SN_LENGTH=14
WithDataTime=0
[Selection]
SelectProduct=PAC_UIX8910_MODEM
[Selinux]
Data=Selinux:-
[Serial port]
Baud rate=115200
Port=23
[Settings]
CheckDriverVer=1
SkipFileID=
WaitTimeForNextChip=0
MustFileID=
[UsageStatistics]
Exsrv=\\10.0.3.44\phone
Insrv=

[PreloadDLImage]
;0, Disable; 1, Enable
Enable=0

;The FileID can be customized.
;Such as FileID=My_preload.
FileID=My_preload

;Base name of the img file.
;Such as my_preload00011010,it base name is my_preload.
ImageNameBase=my_preload

[IQDynamicData]
Enable=0
Offset=
Value=

[WriteFlash]
[default]
[PAC_UIX8910_MODEM]
PREPACK=1@D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ImageFiles\_DLFiles_3BB8_430C853_0\cat1_UIS8915DM_BB_RF_SS_NoVolte_cus_prepack.cpio
FMT_FSSYS=0@
FLASH=1@
AP=1@D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ImageFiles\_DLFiles_3BB8_430C853_0\Customer_cat1bis_novolte.sign.img
APPIMG=1@D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ImageFiles\_DLFiles_3BB8_430C853_0\hello_flash.img
BOOTLOADER=1@D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ImageFiles\_DLFiles_3BB8_430C853_0\boot.sign.img
HOST_FDL=1@D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ImageFiles\_DLFiles_3BB8_430C853_0\fdl1.sign.img
FDL2=1@D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ImageFiles\_DLFiles_3BB8_430C853_0\fdl2.sign.img
PHASECHECK=1@
NV=1@D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ImageFiles\_DLFiles_3BB8_430C853_0\cat1_UIS8915DM_BB_RF_SS_NoVolte_cus_nvitem.bin
PS=1@D:\River\DTU_FCT\EXEs\RESEARCHDOWNLOAD_R22.19.1701_DUT1\Bin\ImageFiles\_DLFiles_3BB8_430C853_0\cat1_UIS8915DM_BB_RF_SS_NoVolte_cus.img
[ReadPartitions]
