[Print]
IP = "169.254.73.180"
Port = "9100"

[CAM_FOLDER]
CAM_PATH= "D:\DTU_EOL\Camera_Images\D\DTU_EOL\Camera_Images/169.254.73.187\VS\Camera\GraphicImages/0009_DTU_EOL_Trail"
replace_path = "D:\DTU_EOL\Info\Configuration\Camera"
ref_img_path = "D:\DTU_EOL\Info\Configuration\Reference_Images"

[CAM_FOLDER_RY]
CAM_PATH= "D:\DTU_EOL\Camera_Images\D\DTU_EOL\Camera_Images/169.254.73.187\VS\Camera\GraphicImages/0002_DTU_EOL_RY"
replace_path = "D:\DTU_EOL\Info\Configuration\Camera_RY"
ref_img_path = "D:\DTU_EOL\Info\Configuration\Reference_Images"
