#pragma once
#include "global_def.h"

enum DL_WM_USER_MSG : DWORD
{
    WM_WARN_MESSAGEBOX = ( WM_USER + 1000 ),
    WM_INIT_PACKET,
    WM_STOP_ONE_PORT,
    WM_POWER_MANAGE,
    WM_STOP_AUTODLOADER,
    WM_DWONLOAD_START,
    WM_USER_HELP,
    WM_BINPAC_PROG_MSG,
    WM_REQUIRE_SN,
    WM_TOOL_BAR_TEXT,
    WM_MUTI_SOFTWARE_CONFIG,
    VM_PRELOAD_CONFIG
};

enum OPERATION_STATUS_MSG : DWORD
{
    BM_BEGIN = WM_USER + 1100,
    BM_FILE_BEGIN,
    BM_OPERATION_BEGIN,
    BM_CHECK_BAUDRATE,
    BM_CONNECT,
    BM_ERASE_FLASH,
    BM_DOWNLOAD,
    BM_DOWNLOAD_PROCESS,
    BM_READ_FLASH,
    BM_READ_FLASH_PROCESS,
    BM_RESET,
    BM_READ_CHIPTYPE,
    BM_READ_NVITEM,
    BM_CHANGE_BAUD,
    BM_OPERATION_END,
    BM_FILE_END,
    BM_END,
    BM_UN_TRANSCODE,
    BM_SET_FIRST_MODE,
    BM_SET_PORT,
    BM_STEP_DESCRIPTION,
    BM_SET_IMEI,
    BM_SET_MCP_TYPE
};


struct BM_DL_END
{
    BOOL    bDLEnd;
    uint32  u32Stage;
    DWORD   dwErrCode;
    LPCTSTR lpErrMsg;
};
typedef BM_DL_END* LPBM_DL_END;
typedef const BM_DL_END* LPCBM_DL_END;
